### ISSUE TITLE
buffered producer on high latency network

### ISSUE THREAD

**Issue by jpeer** [mfontanini/cppkafka#154]
it's not a bug, but i couldn't figure it out yet:

here my issue:
* i am sending high nr of messages
* via a transatlantic (high latency) line

every now and then, traffic/latency spikes lead to breach of internal buffer size of librd kafka, and my app crashes due to the associated exception.

What i need is basically a mechanism that catches the QUEUE-FULL exceptions, queues the message in question, and tries later again, all without blocking the traffic generating code that calls the producer.

i read that `buffered_producer` could help here, but i am unsure. can i just use the default settings of `buffered_producer` and use the `produce()` method? That is can i use `buffered_producer` as a drop-in replacement for the producer?

Or do i need to call the flush() method periodically as well after each message then? (i can call it every few seconds, but i cannot call it after each message, as i really need to send things in batches due to the high latency)

thanks a lot for any help!

**Comment by mfontanini** [comment]
I always use the buffered producer directly, as it solves all of those issues for me. You can either produce and periodically call `flush` or you can call [set_max_buffer_size](https://github.com/mfontanini/cppkafka/blob/master/include/cppkafka/utils/buffered_producer.h#L293) so that it gets auto-flushed whenever you try to produce and there's enough messages in the buffer. Note that if you go this way, `produce` may block for longer than expected, given it may eventually have to flush.

I usually just call `flush` manually but my writing patterns are usually done by chunks so I just write a chunk and flush it at the end of it.

**Comment by jpeer** [comment]
thank you a lot for the infos! 
as a follow up question, i see that on QUEUE-FULL, a poll() is done. Is this the only way to recover from a QUEUE-FULL event in kafka? I asking because i need to avoid blocking behavior as much as possible

 i am staring to think that if i want to avoid any backpressure i would almost have to run the whole kafka client in a separate thread, and have my producing client use shared memory queue or similar to pass messages to that thread.

thanks again!

**Comment by accelerated** [comment]
If you don't want to block your producer you can:
* don't call `set_max_buffer_size()` so that the `BufferedProducer` internal queue grows unlimited.
* instead of `produce()` (which can block on queue_full) call `add_message()` from thread 1.
* from thread 2 call `flush()` or `async_flush()` both of which can block if queue is full. If you have lots of backpressure, `flush()` is a better way to go as it blocks and waits for the broker to receive and ACK all messages...this gives it a bit of breathing room. 
* you can now register a callback to be notified when the queue full error happens. In that callback you can simply tell the _upstream_ producer (whatever that is) to pause for a while. Otherwise, just keep calling `add_message()`. Eventually rdkafka will flush it's internal queue. If your upstream producer happens to be a kafka consumer (of some other topic), the consumers can be paused. See consumer api.

**NOTE**: Although `produce` and `async_flush` are asynchronous functions, this is a bit misleading. They are asynchronous from the point of view or waiting or not-waiting for delivery ACKS from the broker, but they can still block when the queue is full.

**Comment by jpeer** [comment]
thank you very much for all the useful information, i have everything i need now! best regards!

**Comment by Naseefabu** [comment]
> I always use the buffered producer directly, as it solves all of those issues for me. You can either produce and periodically call `flush` or you can call [set_max_buffer_size](https://github.com/mfontanini/cppkafka/blob/master/include/cppkafka/utils/buffered_producer.h#L293) so that it gets auto-flushed whenever you try to produce and there's enough messages in the buffer. Note that if you go this way, `produce` may block for longer than expected, given it may eventually have to flush.
> 
> I usually just call `flush` manually but my writing patterns are usually done by chunks so I just write a chunk and flush it at the end of it.

I still don't understand this method, because for some time there will be no events which means those messages still in internal kafka queue and still not produced to the broker, how does that solves it ?
