### ISSUE TITLE
C2491 “cppkafka::BufferedProducer<BufferType,Allocator>::BufferedProducer” definition of dllimport function not allowed

### ISSUE THREAD

**Issue by latermarch** [mfontanini/cppkafka#206]
![image](https://user-images.githubusercontent.com/9695216/60475774-9387c500-9cab-11e9-9779-57c171166ef5.png)
win10 vs2015
I git clone the latest project from the master

**Comment by latermarch** [comment]
anyone helps

**Comment by accelerated** [comment]
Try defining `cppkafka_EXPORTS`

**Comment by latermarch** [comment]
@accelerated 
 thanks ,I tried, and delete the function in  header buffered_producer.h
![image](https://user-images.githubusercontent.com/9695216/60559867-7670f600-9d80-11e9-8363-3623ea6c3fe2.png)

**Comment by steinio** [comment]
Hi. I just got this very issue yesterday. Do I define `cppkafka_EXPORTS` in macros.h, before the conditionals that uses it, and do I define this before building the library as well? Also, his solution of commenting out the method that causes the error, are there any cleaner ways around this problem?

**Comment by accelerated** [comment]
You would need to define it as a CMAKE build parameter such as `-DCMAKE_CXX_FLAGS="<default ompile options> -Dcppkafka_EXPORTS"`. If you're on windows, the default suggested options are [here](https://github.com/mfontanini/cppkafka/blob/master/CMakeLists.txt#L13-L22). In visual studio you just put the -Dcppakfka_EXPORTS I would imagine in the same place as you would in a normal project built by VS compiler (`Project's Properties -> C/C++ -> Preprocessor definitions`).

I see the error explained [here](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2491?view=vs-2019) but the source code in the Buffered Producer seems OK to me. Anyway, try adding the definition above.

NOTE: IF you are trying to build the library, then `cppkafka_EXPORTS` has to be defined. If you are linking you application with the `cppkafka.dll`, then you MUST NOT define this since you are now _importing_ the symbols.

**Comment by steinio** [comment]
This works for me btw, the fix you mentioned. I ran into issues when I tried to use the code that @latermarch commented out, bufferedproducer, which gave an "undecklared identifier for queue1" as well as queue2. I fixed this by simply removing the identifier as show below:

`template <typename BufferType, typename Allocator>
void BufferedProducer<BufferType, Allocator>::swap_queues(QueueType & queue1, QueueType & queue2, std::mutex & mutex)
{
    std::lock_guard<std::mutex> lock(mutex);
    std::swap(queue1, queue2);
}`

I used the flags mentioned above, but my application still asked for the cppkafka.dll when trying to run, I might be misunderstanding something in the process here. I see that I used those flags, as well as using the CPPKAFKA_BUILD_SHARED=true flag, so I might have overwritten some things when building. I'll have to clean and redo it and check what works.

**Comment by latermarch** [comment]
![image](https://user-images.githubusercontent.com/9695216/60634309-12623680-9e41-11e9-9110-974fee10cab3.png)
actually , I  not only commented out the code ,and I put the function body in class where the function defines just like the picture above

**Comment by jimtarrant** [comment]
I too am getting errors like this building my code using Visual Studio 2019 and cppkafka version 0.3.1:

Error C2491 'cppkafka::BufferedProducer<BufferType,Allocator>::BufferedProducer': definition of dllimport function not allowed
Error C2491 'cppkafka::CompactedTopicProcessor<Key,Value>::CompactedTopicProcessor': definition of dllimport function not allowed
Error C2491 'cppkafka::BasicConsumerDispatcher<ConsumerType>::BasicConsumerDispatcher': definition of dllimport function not allowed

It seems that the member function definitions of these classes are not excluded when cppkafka_EXPORTS is not defined i.e. when consuming the headers in client code as opposed to building the shared library.

Attached is a patch to fix this issue.
[cppkafka_EXPORTS.zip](https://github.com/mfontanini/cppkafka/files/4015938/cppkafka_EXPORTS.zip)

**Comment by zhangyongzhe20** [comment]
`ErrorC2491 'cppkafka::BufferedProducer<BufferType,Allocator>::BufferedProducer': definition of dllimport function not allowed.`
I also get the above error while I'm using VS 2015 and used vcpkg manager to install libs cppkafka:x86-windows (version: 0.3.1-2) and librdkafka:x86-windows (version: 1.2.0-2).
