### ISSUE TITLE
problem in generating docs

### ISSUE THREAD

**Issue by soheil08** [mfontanini/cppkafka#26]
Hi,

when I try to generate docs in `build` directory of `cppkafka`, it errors:

`make: *** No rule to make target 'docs'.  Stop.`

I have `ubuntu 16.04` and `doxygen` is installed.

How can I fix that?

**Comment by mfontanini** [comment]
Can you run this inside the `build` directory and post the output?

```bash
grep DOXYGEN CMakeCache.txt
```

**Comment by soheil08** [comment]
of course, 

`DOXYGEN_DOT_EXECUTABLE:FILEPATH=DOXYGEN_DOT_EXECUTABLE-NOTFOUND
DOXYGEN_EXECUTABLE:FILEPATH=DOXYGEN_EXECUTABLE-NOTFOUND
//ADVANCED property for variable: DOXYGEN_DOT_EXECUTABLE
DOXYGEN_DOT_EXECUTABLE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: DOXYGEN_EXECUTABLE
`

**Comment by mfontanini** [comment]
As you can see, it says "NOTFOUND". You probably run cmake, then installed doxygen and only then tried to run `make docs`. Since CMake caches these values, you're left with the variables that were set when you didn't have doxygen.

Just remove the build directory, create it, run cmake and run `make docs`. That should do it.

**Comment by soheil08** [comment]
That works! thanks
