### ISSUE TITLE
How to send struct to consumers?

### ISSUE THREAD

**Issue by Isabek** [mfontanini/cppkafka#37]
I have a structure as shown below:

```c++
typedef unsigned char byte;

struct Payload {
    unsigned int width;
    unsigned int height;
    vector<byte> data;

    Payload(unsigned int width, unsigned int height, vector<byte> data) :
            width(width),
            height(height),
            data(std::move(data)) {}
};
```

```c++
//producer
vector<byte> data;
data.assign(frame.datastart, frame.dataend);
Payload payload(100, 100, data);
vector<byte> buffer(sizeof(object));
memcpy(&buffer[0], &object, sizeof(object));
builder.payload(Buffer(buff))
```

```c++
//consumer
const cppkafka::Buffer &buffer = msg.get_payload();

unsigned char data[buffer.get_size()];
for (int i = 0; i < buffer.get_size(); i++) {
     data[i] = buffer.get_data()[i]; 
}
Payload *payload = reinterpret_cast<Payload *>(data);
cout << payload->data.size() << endl; // 30000
cout << payload->data[0] << endl; // ERROR
```

And I aim to send it to consumers. First, I serialize it to array of bytes, then create buffer and send it to consumer from producers. 

On consumer side I deserialize the message, and try to get values from payload's data field. Unfortunately I get an error. But, I can get width and height fields. Where am I doing wrong?

**Comment by mfontanini** [comment]
This is not really a cppkafka specific question. A `vector` will contain its data on the heap, so if you serialize one as you're doing, you'll be serializing some pointer values rather than the data itself.

You can either use something that uses local storage rather than the heap (e.g. `std::array`) or instead serialize this properly by serializing each element into the buffer along with some field that indicates the amount of elements present.

**Comment by Isabek** [comment]
Thank you, @mfontanini.
