### ISSUE TITLE
How to deal with the issue of local queue full?

### ISSUE THREAD

**Issue by feifeidadi** [mfontanini/cppkafka#42]
Hi,

I'd like to send 1 million messages to Kafka broker in one loop (queue.buffering.max.messages parameter configured to 1 million).

Pseudo code is as follows:
===
    Buffer buffer(buf, length);  // buf has already been allocated.
    builder.payload(buffer);
    for(long i = 1; i <= 1000000; i++) {
        producer.produce(builder);
    }
    while (producer.get_out_queue_length() > 0) {
        producer.poll();
    }
===

The above code works fine (1 million msgs sent successfully) in case of buffer length is 740 bytes, but it will be failed with below exception (after delivering 370,000+ messages) in case of buffer length increasing to 2855 bytes.
    terminate called after throwing an instance of 'cppkafka::HandleException'
      what():  Local: Queue full
    ./pump: line 1:  8797 Aborted
===

Do you have any suggestion on this issue? Any other parameters need to be configured for the producer?
Or I need to split the loop into several pieces, e.g. sending 100,000 messages every time?

Thanks & best regards,
Mike

**Comment by mfontanini** [comment]
The internal queue in the producer has a fixed size (this is in rdkafka's internals). You need to periodically poll so that the messages are actually sent and not just stuck in the queue.

You can use the [BufferedProducer](https://github.com/mfontanini/cppkafka/blob/master/include/cppkafka/utils/buffered_producer.h) class which will automatically detect that the queue is full and poll for you. Or you can manually poll, however you prefer.

**Comment by feifeidadi** [comment]
Ok, let me try with BufferedProducer instead, thanks a lot Matias Fontanini.
