### ISSUE TITLE
Terminate called after throwing an instance

### ISSUE THREAD

**Issue by ilkeraltay** [mfontanini/cppkafka#44]
hiii,

i am having an error when i am trying to publish a message  to a server using cppkafka (with the simple example code you given) in ubuntu. But i don't see this problem when publishing it to a topic in my computer. Do you have any suggestion ?

The problem is :
**terminate called after throwing an instance of 'cppkafka::HAndleException' what():  Local: Timed out**

thank you

**Comment by mfontanini** [comment]
Do you know what's throwing? Is it connecting to the server or is it when producing a message? Are you sure you are using the right endpoint for the Kafka server and that you can actually reach it?

**Comment by ilkeraltay** [comment]
I have solved the problem by adding sleep(10) function. Now it communicates. I don't why.

thank you, regards

**Comment by zg9uagfv** [comment]
i got the same error, my code:
`
    // Actually produce the message we've built
    producer.produce(builder);
    producer.flush();`

**Comment by orwel1984** [comment]
I am having the same issue..

This happened after setting the kafka config/server.properties file:
listeners=192.168.0.1:9092 

The python producer/consumer works but now the cppkafka producer sometimes throw this error randomly even though there is a flush at the end of the consumer.

**Comment by orwel1984** [comment]
strange that this library has so many bugs

**Comment by mfontanini** [comment]
> strange that this library has so many bugs

If that bothers you, you are always welcome to:

* Not use this library
* Try to fix bugs you find. The amount of code is small enough that this should be trivial if the error is in cppkafka and not librdkafka. This is a *very* slim wrapper on top of librdkafka so you shouldn't have any issues going through the source code.
* Not complain, given the library is free and you shouldn't complain that free things are bad, right?

In this particular case, this is an issue with librdkafka. I actually to change some tests because this seems to happen often. I think given everything is asynchronous in librdkafka, the initial connection phase doesn't necessarily have to happen before you start using the rdkafka handles. I noticed this one particularly when calling flush on a producer but this happens across the board with different calls.

Please create an issue in the librdkafka repo and post the link here so we can keep track of it.
