### ISSUE TITLE
auto.offset.reset=latest not working

### ISSUE THREAD

**Issue by fmvin** [mfontanini/cppkafka#76]
Trying to consume only the messages that produced after consumer starts. For testing I added in `examples/kafka_consumer_dispatcher.cpp` explicit configuration for `auto.offset.reset` before creating of consumer:
```
TopicConfiguration topic_config = {
      {"auto.offset.reset", "latest"}
    };
config.set_default_topic_configuration(topic_config);
```
Start the producer and produce some messages:
```
./kafka_producer -b localhost -t mss -p 0
```
Next start the consumer and received all messages (I expect to get **no messages**). 
```
./kafka_consumer_dispatcher -b localhost -t mss -g 0
```
This issue related to:
1. https://github.com/mfontanini/cppkafka/issues/1. BTW solution with `assign` looks like works fine.
1. https://github.com/edenhill/librdkafka/issues/607

Env:
1. Ubuntu 18.04
2. kafka_2.12-1.1.0
2. librdkafka - last master (ID f26b9b244945b3260ca40814df22ccd6ee779e80)
3. cppkafka - last master (ID 429ec923691e587603db5a4b5fba221e4bb0d9ba)

**Comment by mfontanini** [comment]
I just tried this and it works as expected, I'm using rdkafka 0.9.5. Keep in mind that the offset reset policy just means "if there *is not* an offset for this consumer in this topic/partition, then use this policy". This means that if you do this:

* Start consuming
* Produce 1 message
* Consumer sees the message and commits it
* Stop consumer
* Produce 1 message
* Start consumer

Then the consumer will see that one new message because it *did* have an offset but this new message has an offset larger than the last committed one, hence you receive the message.

**Comment by fmvin** [comment]
Then please advice an appropriate solution how to consume only these messages which are produced after consumer starts.

**Comment by mfontanini** [comment]
You can just not commit any messages and use reset policy latest. That way there's never an offset committed for a topic/partition for that consumer, hence every time you'll start at the end of each queue.

**Comment by fmvin** [comment]
> You can just not commit any messages and use reset policy latest. That way there's never an offset committed for a topic/partition for that consumer, hence every time you'll start at the end of each queue.

It works now as I expected. Thanks a lot.
